### ISSUE TITLE
Secret RGSoC video!

### ISSUE THREAD

**Issue by anasofiapinho** [rails-girls-summer-of-code/announcements#1]
Hey everyone! As we are halfway through the program and things are getting calmer, we were thinking about **surprising everyone by making a small video with clips from all the people who are part of RGSoC 2016!** Yes, this means, students, coaches, mentors, coaching companies and organizers! **You are all invited to be part of this! <3**

With this video we hope to inspire even more women to become software developers and contribute to open source. We also hope to open doors for the students in the next editions by promoting RGSoC, whether it would mean that we can reach more potential coaches or mentors, and their projects, or by getting more coaching companies and sponsors enthusiastic about helping out. Last but not least, we believe it will be amazing to see in a video what’s like to be part of RGSoC!

As we don’t want to to lose a lot of time with this, I need to let you know that the goal of the video is not to look perfect. It’s to look real and for us to have fun!

**If you have any questions, please comment on this issue or send me (@anasofiapinho) or Arrchana (@arrchana) a message on slack!**
### IMPORTANT INFORMATION

**The deadline will be the 25th of September.**

**You can find the guidelines here:**
[https://www.dropbox.com/s/essndfsv9wzqz1z/RGSoC%202016%20Video%20Guidelines.pdf?dl=0](https://www.dropbox.com/s/essndfsv9wzqz1z/RGSoC%202016%20Video%20Guidelines.pdf?dl=0)

**To upload the videos go to this link:**
[https://www.dropbox.com/request/SzPOSZbQyiqSj04VmwKC](https://www.dropbox.com/request/SzPOSZbQyiqSj04VmwKC)

**Please take into account that when you upload the videos, you agree to give the copyrights to Rails Girls Summer of Code, who will use the videos for communication and marketing purposes.
Your name will appear in the video, so please add your name to the clip file name with other important information on the “How to send the videos” section.**

**Comment by arrchana** [comment]
Hi @anasofiapinho I have edited a few typos and made some small changes for the post. Where can I edit the guidelines pdf?

Hey everyone! As we are halfway through the program and things are getting calmer, we were thinking about **surprising everyone by making a small video with clips from all the people who are part of RGSoC 2016!** Yes, this means, students, coaches, mentors, coaching companies and organizers! **You are all invited to be part of this! <3**

With this video we hope to inspire even more women to become software developers and contribute to open source. We also hope to open doors for the students in the next editions, by promoting RGSoC, whether it would mean that we can reach more potential coaches or mentors, and their projects, or by getting more coaching companies and sponsors enthusiastic about helping out. Last but not least, we believe it will be amazing to see in a video what’s like to be part of RGSoC!

As we don’t want you to lose a lot of time with this, we want to let you know that the goal of the video is not to look perfect. It’s to look real and for us to have fun!

If you have any questions, please comment on this issue or send me (**@anasofiapinho**) or Arrchana (**@arrchana**) a message on slack!
# IMPORTANT INFORMATION

**The deadline will be the 25th of September.

You can find the guidelines here:**
https://www.dropbox.com/s/pfb8sdwfxzuqkqy/RGSoC2016VideoGuidelines.pdf?dl=0

**To upload the videos go to this link:**
https://www.dropbox.com/request/SzPOSZbQyiqSj04VmwKC

**Please take into account that when you upload the videos, you agree to give the copyrights to Rails Girls Summer of Code, who will use the videos for communication and marketing purposes.
Your name will appear in the video, so please add your name to the clip file name with other important information on the “How to send the videos” section.**

**Comment by anasofiapinho** [comment]
Hey @arrchana! Thanks! You can edit things here: https://docs.google.com/document/d/1M-Ejc3vnoVNmpSmOm5SvnK0slvLXAaiM153etaxoPE0

**Comment by arrchana** [comment]
Should we mention any timezone for the deadline? I have edited the deadline to read as follows:

### Deadline

Please send the clips latest by the **25th of September**.

**Comment by arrchana** [comment]
I have made a few edits in the Guidelines doc @anasofiapinho
