### ISSUE TITLE
Kick Off RGSoC 2017 - Celebration in Berlin @Travis CI

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/announcements#12]
We want to start this year's Rails Girls Summer of Code program up with all of you wonderful Berlin people. Everyone is invited: RGSoC past and current participants, coaches, mentors, organizers, sponsors, supervisors, supporters and friends. :purple_heart: :yellow_heart: :green_heart: :heart:  

sponsored by:

![nh_logo](https://user-images.githubusercontent.com/1711357/27378721-0975d480-5679-11e7-9969-5cc6667c99c5.png)

**Details**: Let's meet for a nice BBQ on the Travis CI roof terrace. We will provide some water and non-alcoholic drinks and ask you to stay on the _mostly_  alcohol-free side of drinks that you bring, thank you 🙇 .

**What:** A bbq picnic - bring some food and we'll share all the things 
**When:** Friday, 30th of June 2016, 6pm CEST - 9 pm CEST
**Where:** At Travis CI Gmbh, [Rigaer Str. 8],  Ring "Tessa"-  it's on the 3rd floor.
 (https://www.google.de/maps/place/Travis+CI+GmbH/@52.5178732,13.4535313,17z/data=!3m1!4b1!4m5!3m4!1s0x47a84e6700ca7771:0x8eebbb66a945d599!8m2!3d52.51787!4d13.45572?hl=en), near Frankfurter Tor/ Bersarinplatz! 

![screen shot 2016-07-07 at 10 01 07](https://cloud.githubusercontent.com/assets/1711357/16646320/c72187f8-4429-11e6-920b-13f5804d0334.png)
### This event is organized under the [Berlin Code of Conduct](http://berlincodeofconduct.org/), please read this carefully and only attend if you agree and abide by this. We will enforce the CoC.

**RSVP** with a comment if you want to come and **mention what you are planning to bring for noms** 🍔 🍞 🍌 🍅 🍏 🍤 🍉 🍗 🌽  🍒 🌰 🍍  :sparkles:

**Comment by anikalindtner** [comment]
🙋 I'm in and will bring 10 sausages for the BBQ.

**Comment by bitboxer** [comment]
I will bring 🍉

**Comment by schultyy** [comment]
`self.attend()`

**Comment by Nienor** [comment]
MOI! +1

**Comment by Rete2** [comment]
I'll be there (Team Code Bears) and will bring some food, will let you know later which kind (maybe a salad or some vegetables)

**Comment by infraredgirl** [comment]
I'll be there and bring a few burgers and drinks.

**Comment by daiyi** [comment]
I'll be there! I'll bring some vegan food.

**Comment by id-gue** [comment]
I'll be there (team nk42) and bring some vegetarian food.

**Comment by mddemarie** [comment]
I'll be there (team nk42) and bring bread, hummus and tomatoes.

**Comment by snordhausen** [comment]
I'll be there (team nk42) and bring random food and/or beer.

**Comment by carpodaster** [comment]
✋  (with a 85cm tall +1 who's always ready to raid a buffet)  Will bring 🍞 / 🥖 w/ dips.

**Comment by jenni** [comment]
attending too! (team berlindiamonds), will bring some spontaneous food

**Comment by schultyy** [comment]
Will also bring some food and beverages

**Comment by regexident** [comment]
I'm in, won't make any time before 7pm though. 😢

**Comment by ThisIsMissEm** [comment]
I might try to stop by; not sure if I'll make it though

**Comment by janl** [comment]
+1

**Comment by juliusv** [comment]
:+1: will bring something random!

**Comment by plexus** [comment]
I'll be there!

**Comment by laushinka** [comment]
Attending! Will bring veggies and/or fruits.

**Comment by fannivuniconnu** [comment]
In! I'll bring vegetables to and some veggie/vegan things to grill

**Comment by endocrimes** [comment]
👍🎉 - not sure what I'll be bringing yet

**Comment by lucaspinto** [comment]
I'll be there with food and drinks :)

**Comment by aquaranto** [comment]
Nick and I will be there with the boys :) and some food to share

**Comment by joanwolk** [comment]
I'll bring a couple of bags of chips!

**Comment by joepvd** [comment]
I'll be there and bring a toddler and something random to eat and/or drink.

**Comment by xhr15** [comment]
rokken_roll()

**Comment by nynnejc** [comment]
Will be spiritually present -celebrating from Copenhagen this year!

**Comment by arduina** [comment]
I'll bring something weird!

**Comment by hom3mad3** [comment]
me, +1 and vegan quiche

**Comment by kajatiger** [comment]
I might bring some fish and some soft drinks :)

**Comment by daisyt** [comment]
I'll bring something healthy!

**Comment by vsmart** [comment]
I will be there ✨ Also it's critical mass bike ride 🚲 the same day, I will go there afterwards, feel free to join :D

**Comment by andoneve** [comment]
i have to work until 8, but will come after! xo

**Comment by netagonen** [comment]
I will be there and bring smth vegan to put on the grill (hamburgers or sausages)

**Comment by sarahkami** [comment]
Will be there - and bring something

**Comment by dmt** [comment]
I'll be there but will probably be late

**Comment by porras** [comment]
I'll try to join but not on time for food I think. We can still share some alkoholfrei weißbier (they're on me)!

**Comment by anikalindtner** [comment]
please feel free to bring all the rainbow swag you can find :rainbow_flag: ❤️ :rainbow_flag: 💛 :rainbow_flag: 💚  :rainbow_flag:

**Comment by hagenburger** [comment]
I’ll try to join at least for a bit, most likely not for food. See you!

**Comment by siemieniec** [comment]
I will join and bring some fruits.

**Comment by jancborchardt** [comment]
Will try to join too, lilely not for food. cc @jospoortvliet as well :)

**Comment by jospoortvliet** [comment]
Hey, I didn't know about this! I'd like to join but have another appointment, let me see if I can move that... @camilasan perhaps you're interested too?

**Comment by jospoortvliet** [comment]
Ok I will join and bring random stuff from the supermarket close by... anything needed?

**Comment by jospoortvliet** [comment]
Btw how will we deal with this water-from-the-sky thing that tends to be BBQ unfriendly?
