### ISSUE TITLE
Kick Off RGSoC 2017 - Celebration in Tirana @Open Labs

### ISSUE THREAD

**Issue by jonatoni** [rails-girls-summer-of-code/announcements#13]
We (Xheni and me) want to organize an event at Open Labs Hackerspace, the first Albanian based not for profit community that promotes open knowledge initiatives, with all the people that want to join the event. We will talk about Rails Girls Summer of Code Intership, how it works and how someone can be part of it. We will also have a video call with our mentor and coaches (if they will be available). In the end we will have some drinks and sweets all together. 🍰🍦🍩🍪🍭🍬🎉🎉

Details: Bring your own bottle to have some discussions together and have fun. 🎉🍺🍻🍷🥂🍸🍹🍾🎉
When: Saturday, 1st of July 2017, 6pm CEST - 8 pm CEST
Where: Open Labs Hackerspace
http://osm.org/go/xexSkuF7t?m=

**Comment by alicetragedy** [comment]
That's awesome @jonatoni & @xh3n1 👏

**Comment by jonatoni** [comment]
![rgsoc](https://user-images.githubusercontent.com/8283009/27501180-0368c1e8-586c-11e7-9bdd-5d4f2f9157b4.png)
Here is the image we have created for the event :)

**Comment by jancborchardt** [comment]
Confirming I can join via video call. :) cc coaches @nickvergessen @MorrisJobke

**Comment by alicetragedy** [comment]
I'll be joining via video call, too — just to say hello :)

**Comment by nickvergessen** [comment]
Should be available via video as well

**Comment by jancborchardt** [comment]
We can use our video calls app in Nextcloud :) https://cloud.nextcloud.com/call/nrkt

cc @jonatoni @xh3n1 @nickvergessen @morrisjobke @Henni @irgendwie @MariusBluem whoever wants to join. :)

**Comment by alicetragedy** [comment]
I took a couple of screenshots of the call just in case — I'll send them to you by email, and maybe you can decide if you want to share them in slack and/or twitter, Xheni @jonatoni @jancborchardt? Didn't want to post it anywhere without your explicit consent :)

**Comment by xh3n1** [comment]
Hi@alicetragedy!  Yes, sure  you can share them on social media :) . Please, send them to us by email, so we can add them to our blogpost too.
