### ISSUE TITLE
Kick Off RGSoC 2017 - Celebration in Vienna

### ISSUE THREAD

**Issue by mkalininait** [rails-girls-summer-of-code/announcements#14]
We are planning a small kick-off celebration in Vienna and would like to invite everyone who feels relevant to RGSoC: students, alumnae, coaches, mentors, organizers, sponsors, supervisors, supporters and friends! 

**Where:** Adria on Donaukanal, http://www.adriawien.at/
**When:** Friday, 30th of June 2017, 5pm - 8pm local time.

There is no special program; we will meet, drink something refreshing, eat small foods, relax and talk! 

**Note:** this event is organised under the [Code of Conduct](https://railsgirlssummerofcode.org/about/code-of-conduct/). Please read it carefully and only attend if you agree and abide by this.

**RSVP** with a comment if you want to come! 🙌  🐝 🙌🏻   🐹  🙌🏼  🌸  🙌🏽  🍒  🙌🏾  🍹 🙌🏿

**Comment by mkalininait** [comment]
@alicetragedy @ramonh @althaire @michaelem @klappradla (in case you are in Vienna) @cypher @mxstbr @mitsuhiko we would love to see you on the celebration! If you know someone we forgot to mention, please ping them here. Your +1s you are also welcome!

**Comment by alicetragedy** [comment]
I'll be there 🙋

**Comment by hola-soy-milk** [comment]
~~Yes! Would love to join, thank you!~~ So sorry, I realized I already am booked for that evening 😭

**Comment by michaelem** [comment]
🙋‍♂️

**Comment by cypher** [comment]
🙋‍♂️

**Comment by mitsuhiko** [comment]
Will be there!

**Comment by doesterr** [comment]
Hi, will be there as well, sorry for the short notice.

We (Runtastic) are a first time sponsor this year, after Max pitched that idea within the company.

**Comment by alicetragedy** [comment]
Awesome! Cool to have you join our humble get-together, @doesterr! 🎉 ✨

**Comment by alicetragedy** [comment]
Thanks everyone for joining! 🙌
