### ISSUE TITLE
Kick Off RGSoC 2017 - Celebration in New Delhi @IIIT Delhi

### ISSUE THREAD

**Issue by brihijoshi** [rails-girls-summer-of-code/announcements#15]
Hey all!

Let's get started with Rails Girls Summer of Code program 2017 with a little celebration. Join us as we chat and share our experiences, along with a good pizza treat pooled by the attendees :raised_hands: :smile:

**Details** - Open talks on our experience with Open Source, along with those shared by RGSoC alumni, with Pizzas alongside, preferably pooled :pizza: :ice_cream: :wine_glass: :fries: :cookie:

**When & Where** - IIIT Delhi Campus, New Delhi -- _2nd July, Sunday, 12 PM (IST) onwards_ (You may follow Part 1 of this link -- http://cerc.iiitd.ac.in/contact.html for directions)

**Who** - Everyone who's supported RGSoC --  the past and current participants, coaches, mentors, organizers :raised_hands: :raising_hand:

Join us in beginning RGSoC 2017 with a bash! 🎉🎉 

Please RSVP in the comments to confirm :smiley: :smiley:

**Comment by apoorvasingh17** [comment]
Can students from other colleges attend ?

**Comment by brihijoshi** [comment]
@apoorvasingh17 Yes! Sure 😄 Looking forward to meeting you

**Comment by Nidhiya** [comment]
Looking forward to meeting you all :) :D
-Nidhiya 
( RGSoC 15 Fellow )

**Comment by kuldeepaggarwal** [comment]
@akshay-vishnoi

**Comment by brihijoshi** [comment]
Hey all! We're starting soon 😁
