### ISSUE TITLE
Kick Off RGSoC 2017 - Celebration in Colombo, Sri Lanka (🇱🇰)

### ISSUE THREAD

**Issue by Janakshi28** [rails-girls-summer-of-code/announcements#16]
Hey everyone!

To start our Rails Girls Summer of Code journey with joy, we are planning a tiny kick-off celebration in Colombo, Sri Lanka, on the very first RGSoC 2017 working day it self! 💻☕😁✨

Let's get together to talk about the upcoming journey together while having a cup of coffee, not to mention, cutting the special cake to celebrate the start! ☕🎂🍰🌭🍔🍩🍪🍹🎉🎉🎉

**When:** Monday, 3rd of July 2017, 9.30 am (local time) onwards
**Where:** Sen-Saal - Hyde Park
(Follow this link -- https://goo.gl/maps/CYdQh1Lwmbv ), near APIIT Sri Lanka!
**Organizers:** Students from Team Fusion 
We would like to invite all of our friends from the RGSoC family to join us. (students, coaches, mentors, supervisors, supporters and friends) 
Please RSVP with a comment. 🙂

**Comment by kalpanibhagya** [comment]
Hi everyone,

Summer is getting even hotter since the rgsoc at our doorstep. I know the whole rgsoc family is excited as I am. 😊😊 To turn that excitement to a joy,  come join us with the team fusion to celebrate our lead-off to a wonderful three month journey ahead.  All are warmly welcome with open arms. 🎊🎂🎉🎊🎂🎉

**Comment by tharindu123** [comment]
Unfortunately I will not be able to join the kick-off meeting since I'm in an official visit to IFS Germany. Anyway, I hope you guys will have a nice time together. :)

**Comment by Janakshi28** [comment]
Oh we missed you both at our kick off celebration yesterday.., @tharindu123  and @ImranHishaam .. So we had to finish eating the cake without you two.. Sorry! 😅🎂🍰🎉
