### ISSUE TITLE
End of RGSoC 2017 - Celebration in Berlin @Mozilla, Sept 22nd 

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/announcements#17]
We want to end this year's Rails Girls Summer of Code program up with all of you wonderful Berlin people. **Please RSVP** if you want to join - this way we know how much food to order! 

**Who is welcome?**: everyone is welcome - wether you are already part of RGSoC or not 💕 
**What:** An evening with lightning talks from the Berlin teams and time to chat
**When:** Friday, 22nd of September 2016, 6 pm CEST - 9pm CEST
**Where:** At the [Mozilla Berlin office](https://wiki.mozilla.org/Berlin_Office#Berlin_Office_Location) 
**Drinks/Food**: There will be pizza from La Pausa (vegan, vegetarian and with meat)🍕and several non-alcoholic drinks!

### This event is organized under the [Berlin Code of Conduct](http://berlincodeofconduct.org/), please read this carefully and only attend if you agree and abide by this. We will enforce the CoC.

**RSVP** with a comment if you want to come and if you are bringing a +1 +2 +3... :sparkles:

**Comment by anikalindtner** [comment]
👻

**Comment by michaelem** [comment]
🙋‍♂️

**Comment by janogonzalez** [comment]
🐗

**Comment by bitboxer** [comment]
✊🏼

**Comment by katrinkampfrath** [comment]
🐿

**Comment by daiyi** [comment]
:sparkles:

**Comment by killerkiara** [comment]
🔮  + 🐗

**Comment by regexident** [comment]
🐒

**Comment by Realtin** [comment]
🐳

**Comment by alonpeer** [comment]
👽 🍐

**Comment by klappradla** [comment]
🐒

**Comment by infoverload** [comment]
:crystal_ball:

**Comment by robinboening** [comment]
🤖  ➕  :two:

**Comment by daveliepmann** [comment]
![i'll be there](https://25.media.tumblr.com/5517176b2cd75f917994b41c4d439d6e/tumblr_misjuyGbb81s5basgo4_250.gif)

**Comment by davidpiegza** [comment]
🐶

**Comment by mockturtlesoup** [comment]
:crocodile: + 1

**Comment by plexus** [comment]
🚩

**Comment by BanzaiMan** [comment]
🙋‍♂️

**Comment by ttaubert** [comment]
🐝 +1

**Comment by janl** [comment]
🕵🏻

**Comment by kajatiger** [comment]
💃  + 3

several people have asked me for a schedule. when are we supposed to start with our lighting talks?
@anikalindtner

**Comment by netagonen** [comment]
:cat:

**Comment by saskali** [comment]
:octopus:

**Comment by carpodaster** [comment]
:thinking: :thought_balloon: { :baby: }

**Comment by jobs-betterplace** [comment]
me

**Comment by linberg** [comment]
🤓 + 1

**Comment by jobs-betterplace** [comment]
👍

**Comment by lisbethmarianne** [comment]
🦊

**Comment by langjoh** [comment]
☕️  +1

**Comment by porras** [comment]
🙈

**Comment by matthiasr** [comment]
👻

**Comment by ferbsx** [comment]
🦋 ➕1

**Comment by vladiepure** [comment]
me + 1

**Comment by shushugah** [comment]
🦄 𝑿 2

**Comment by zfhui** [comment]
👾

**Comment by thatbettina** [comment]
🌈

**Comment by vonneudeck** [comment]
🦉

**Comment by lauralindal** [comment]
I'll be there, with @chiramiso \o/ 
![joylorelai](https://user-images.githubusercontent.com/5703164/30476351-0ba2c770-9a0a-11e7-8e70-ab61c827209e.gif)

**Comment by bl00dymarie** [comment]
mememe :heart_eyes_cat: +1 :computer:

**Comment by mddemarie** [comment]
✨

**Comment by starkcoffee** [comment]
💃

**Comment by chrisokamoto** [comment]
What will be the lightning talks about?

**Comment by miguelgraz** [comment]
:snowboarder:

**Comment by id-gue** [comment]
+2

**Comment by anikalindtner** [comment]
@chrisokamoto the Berlin teams of this year's RGSoC edition will present themselves and what they've worked on during the last 3 months.

**Comment by lislis** [comment]
💃 +1

**Comment by BriocheBerlin** [comment]
:bowtie:

**Comment by jackrusher** [comment]
🚴

**Comment by anikalindtner** [comment]
@kajatiger sorry, just saw this now. there is no fixed start date for the talks, we usually start when most ppl have arrived (~30-40 min after beginning).

**Comment by leyink** [comment]
Commeting with a potential +1 !

**Comment by patriciaschulz** [comment]
me + 1

**Comment by mhuebert** [comment]
🐯🦁 1+1

**Comment by jasminechao** [comment]
🐯

**Comment by ariaru** [comment]
Planning to be there, :heavy_plus_sign: :one: 
:)

**Comment by backspace** [comment]
👋 😀

**Comment by mk** [comment]
😺

**Comment by johannhof** [comment]
I'll be there

**Comment by fepa** [comment]
I'll be there as well! 👋

**Comment by dmt** [comment]
me + 1

**Comment by arduina** [comment]
🐙

**Comment by kasteph** [comment]
🐒

**Comment by eugenpirogoff** [comment]
self + 1

**Comment by nilshaebel** [comment]
🤘🏿

**Comment by aydamacink** [comment]
me + 1

**Comment by id-gue** [comment]
Hi, does anyone knows if the videos of the talks are available somewhere?

**Comment by johannhof** [comment]
@id-gue The full event recording is here: https://air.mozilla.org/end-of-rgsoc-2017-celebration/

@ttaubert might be able to provide the individual talks as files

**Comment by alicetragedy** [comment]
Would it be ok to share the link to this via social media / in our official RGSoC wrap-up blog post? (not sure we'll be doing that yet, but just wanted to ask upfront) 
thanks so much for taking care of the logistics @anikalindtner @ttaubert (and whoever else was involved in organising this event, as I don't have a full overview).

**Comment by ttaubert** [comment]
Totally fine with me to share the link anywhere you want :)

**Comment by kajatiger** [comment]
I'm coming, too 🤗 
What about the RGSoC Kick Off event, is there one as well this year?
