### ISSUE TITLE
End of RGSoC 2017 - Celebration in Amsterdam, Sept 29th

### ISSUE THREAD

**Issue by JessicaML** [rails-girls-summer-of-code/announcements#18]
Team impact devs in Amsterdam are having a farewell RGSoC party!

Who is welcome?: everyone is welcome - wether you are already part of RGSoC or not 💕
What: An evening of beer and bitterballen
When: Friday, 29th of September 2016, 6pm 
Where: Café De Sluyswacht, Jodenbreestraat 1, 1011 NG Amsterdam

**Comment by emcoding** [comment]
Have fun!! I won't be there, but I'll drink a beer and cheer for you all!

**Comment by alicetragedy** [comment]
I'm in Amsterdam until Saturday and I'd love to join your party (or rather, drop by before dinner). Hope that's ok <3 ✨

**Comment by JessicaML** [comment]
Yaaaaaaasssss! please join! Here's my number = 0044 7913 658 294

**Comment by alicetragedy** [comment]
@JessicaML I think @acnagy would potentially be interested in joining too... and maybe other people from Travis CI would join. Would that be ok if I shared this link and asked them to rsvp as well?

**Comment by alicetragedy** [comment]
closing this :)
