### ISSUE TITLE
End of RGSoC 2017 - Celebration in Copenhagen, October 1st

### ISSUE THREAD

**Issue by nynnejc** [rails-girls-summer-of-code/announcements#19]
Alumni & 1 student is throwing a RGSoC party in Copenhagen!

Who is welcome?: everyone is welcome - wether you are already part of RGSoC or not 💕
What: Drinks and celebrations for this wonderful community
When: Sunday, October 1st 2017, 8pm
Where: Cafe Dyrehaven, Sønder Blvd. 72, 1720 København V

**Comment by lauralindal** [comment]
Hey @nynnejc :) I'll be in Copenhagen b/c of the GOTO conference. Depending on how exhausted I'm from the trip, I could join you in this gathering :)

**Comment by nynnejc** [comment]
For anyone interestested in joining we now have a location, the cosy cafe Dyrehaven in the Vesterbro neighborhood of Copenhagen (near central station). We meet at 8pm!

**Comment by alicetragedy** [comment]
So glad this happened! thanks for organising — I'll close this issue now. 🎉 🎊
