### ISSUE TITLE
End of RGSoC 2016 - Celebration in Berlin @SoundCloud 

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/announcements#2]
We want to end this year's Rails Girls Summer of Code program up with all of you wonderful Berlin people. **Please RSVP** if you want to join - this way we know how much food to order! 

**Who is welcome?**: everyone is welcome - wether you are already part of RGSoC or not 💕 
**What:** An evening with lightning talks from the Berlin teams and time to chat
**When:** Friday, 30th of September 2016, 7 pm CEST
**Where:** At SoundCloud HQ, [Rheinsberger Str. 76/77](https://www.google.de/maps/place/Soundcloud+HQ/@52.5068441,13.4247317,10z/data=!4m5!3m4!1s0x47a851f11cea3617:0xd4277880007598c2!8m2!3d52.5368138!4d13.3948607?hl=en) 
**Drinks/Food**: There will be pizza 🍕  and several non-alcoholic drinks!

![screen shot 2016-09-23 at 13 53 31](https://cloud.githubusercontent.com/assets/1711357/18784926/b2268228-8195-11e6-8ac2-42580a126734.png)
### This event is organized under the [Berlin Code of Conduct](http://berlincodeofconduct.org/), please read this carefully and only attend if you agree and abide by this. We will enforce the CoC.

**RSVP** with a comment if you want to come and if you are bringing a +1 +2 +3... :sparkles:

**Comment by anikalindtner** [comment]
I'll be there 🙋

**Comment by lucaspinto** [comment]
There, maybe +1.

**Comment by carlad** [comment]
gonna try and make it

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
Ya, I'll join!

**Comment by bl00dymarie** [comment]
I am definitely in, but might bring some friends, maybe 2 or 3 if this is ok @anikalindtner ?

**Comment by svenfuchs** [comment]
🙋

**Comment by katrin-k** [comment]
👌🏼👍🏼

**Comment by troubalex** [comment]
🙋

**Comment by anikalindtner** [comment]
@lilaluca for sure!

**Comment by nynnejc** [comment]
I'll be there +1

**Comment by lisbethmarianne** [comment]
I'd like to come as well.

**Comment by aydamacink** [comment]
be there with +1 maybe +2

**Comment by bitboxer** [comment]
I will be there <3

**Comment by porras** [comment]
🙋🏼

**Comment by Nienor** [comment]
I'm in with a +1!

**Comment by tat-ableton** [comment]
Joining! Looking forward to seeing what everyone has been working on \o/

**Comment by eta-ableton** [comment]
I'll be joining!

**Comment by froilainhaeckse** [comment]
I will be there and might also bring someone...

**Comment by Realtin** [comment]
I'll be there, If my cold is gone by then

**Comment by ammancilla** [comment]
Count me in! 🎆

**Comment by sareg0** [comment]
I will be there!

**Comment by maxprokopiev** [comment]
I'll join 👍

**Comment by plexus** [comment]
👍🎉🎈

**Comment by joecorcoran** [comment]
I'll be there! Will have to leave early though :|

**Comment by mauditecandela** [comment]
I'll be there :)

**Comment by alexhumphreys** [comment]
I'd like to join :)

**Comment by langjoh** [comment]
I will be there as well :) and with a +1

**Comment by fredericmarx** [comment]
I'd like to join, too 🙋

**Comment by christophwitzko** [comment]
Yay, I'm in. 🎉 💃

**Comment by finnp** [comment]
I'll be there 💁

**Comment by valakirka** [comment]
I'll be there as well! <3

**Comment by boennemann** [comment]
I'd like to join as well with a +1 :)

**Comment by siemieniec** [comment]
I'll be there with +1. :tada:

**Comment by berlintam** [comment]
I'll be there!

**Comment by tingled** [comment]
i will be there with a +1!

**Comment by hegyi** [comment]
I'll be there with +1

**Comment by remydagostino** [comment]
In

**Comment by jules-p** [comment]
Count me in! 🎉

**Comment by ariaru** [comment]
I'll be there if sudden tiredness does not occur until then :)

**Comment by shushugah** [comment]
Will there be vegan pizza? :D also doubles as halal, lactose intolerant friendly too! Either way looking forward!

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
@shushugah fyi, the party was last friday, looks like you missed it!
