### ISSUE TITLE
End of RGSoC 2017 - Celebration in Tirana, October 4th 

### ISSUE THREAD

**Issue by jonatoni** [rails-girls-summer-of-code/announcements#21]
We want to celebrate the end of RGSoC with our local community, [Open Labs](https://openlabs.cc), in Tirana, Albania and share with them our experience. 

Who is welcome?: Everyone is welcome - whether you are already part of RGSoC or not 💕
What: We, Codeaholics team, will share our experience with other girls
When: Wednesday, 4th of October 2017, 4 pm CEST - 6 pm CEST
Where: [At Open Labs Hackerspace](https://openlabs.cc)

**Comment by jonatoni** [comment]
![end_of_rgsoc_in_tirana](https://user-images.githubusercontent.com/8283009/31100787-1d538a26-a7cb-11e7-8be2-0d31bb2762d4.png)

**Comment by alicetragedy** [comment]
closing this issue, since it's already taken place :)
