### ISSUE TITLE
End of RGSoC 2017 - Celebration in Prishtina, October 7th 

### ISSUE THREAD

**Issue by jonatoni** [rails-girls-summer-of-code/announcements#22]
We want to celebrate the end of RGSoC with the local community, [FLOSSK](https://www.flossk.org/), in Prishtina, Kosovo and share with them our experience. This event will be merged with Fedora Women Day and Mini DevConf that will start since 10 am.

Who is welcome?: Everyone is welcome - whether you are already part of RGSoC or not 💕
What: We, Codeaholics team, will share our experience with other girls
When: Saturday, 7th of October 2017, 4 pm CEST - 5 pm CEST
Where: [At Prishtina Hackerspace](http://www.prishtinahackerspace.org/)

**Comment by jonatoni** [comment]
![end_of_rgsoc_in_prishtina](https://user-images.githubusercontent.com/8283009/31100846-595aad4c-a7cb-11e7-803b-ac51e990e8c2.png)

**Comment by jonatoni** [comment]
![end_of_rgsoc_in_prishtina](https://user-images.githubusercontent.com/8283009/31101089-7ffd5eda-a7cc-11e7-9b81-5fcc2c97a5c3.png)

**Comment by alicetragedy** [comment]
@jonatoni don't know if you have any photos, posts, or any material that you want us to share of your end of RGSoC get-together? In any case, I'll be closing this issue since this has taken place. Hope you had a lot of fun!
