### ISSUE TITLE
End of RGSoC 2016 — Celebration in Vienna @ Wirr

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/announcements#3]
We welcome everyone from our community to join us for a small get-together in Vienna's 7th district to celebrate the very last day of RGSoC 2016 🎉 

**Who**: anyone who wants to join; past, present and future participants, volunteers, and organisers!
**What**: a small informal get-together to chat and get to know our community and celebrate yet another successful RGSoC!
**When**: Friday, September 30th 2016, 6:30 pm CEST
**Where**: [Wirr](http://wirr.at/), Burggasse 70 

We will cover some **snacks and non-alcoholic drinks** from Wirr at the start of the evening.
This event is organised under our Rails Girls Summer of Code [Code of Conduct](http://railsgirlssummerofcode.org/about/code-of-conduct/); we ask all attendees to read it and behave in accordance with our CoC. Thank you! ❤️ 

**Please RSVP with a comment below before Thursday, 17:00 CEST, so we know how many people are coming and can reserve a table accordingly.**

**Comment by klappradla** [comment]
I'm in!

**Comment by alicetragedy** [comment]
me too!! ✨ 🎉

**Comment by hola-soy-milk** [comment]
Yasss I wanna join 🚀

**Comment by mxstbr** [comment]
I can't yet say for sure I'll make it, but I'll definitely try!

**Comment by michaelem** [comment]
I'll be there!
