### ISSUE TITLE
End of RGSoC 2016 — Celebration in Brazil @ Raul Hacker Club

### ISSUE THREAD

**Issue by geisasantos** [rails-girls-summer-of-code/announcements#4]
We welcome everyone from our community to join us for a small get-together in Salvador to celebrate the very last day of RGSoC 2016 :tada:

**Who:** anyone who wants to join; past, present and future participants, volunteers, and organisers!
**What:** a small informal get-together to chat and get to know our community and celebrate yet another successful RGSoC!
**When:** Friday, September 30th 2016, 2 pm ~ 10 pm BRT
**Where:** [Raul Hackerspace](http://raulhc.cc/Doc/Sede#ComoChegar), Salvador-BA
**Snacks:** Please, bring some snacks to share with others. There will be water, juice, fruits for vegans and lactose-free. 

It will be an open day at Raul Hackerspace so we planned some activities and talks.
This event is organised under our Rails Girls Summer of Code [Code of Conduct](http://railsgirlssummerofcode.org/about/code-of-conduct/); we ask all attendees to read it and behave in accordance with our CoC. Thank you! :heart:

**RSVP** with a comment if you want to come and if you are bringing a +1 +2 +3... :sparkles: 

**For Portuguese speakers**, please read [our invitation here](http://raulhc.cc/Agenda.2016-09-30-FestaDeDespedidaDoRGSoC) ^.~

![Image of Perifericas](https://perifericas.github.io/files/logo.png)

**Comment by inescoelho** [comment]
I will be joining you via the internet! :)
