### ISSUE TITLE
End of RGSoC 2016 -- Portland, OR, USA

### ISSUE THREAD

**Issue by jeenalee** [rails-girls-summer-of-code/announcements#5]
What better way to celebrate another successful RGSoC in Portland than watching thousands of migrating swifts swirl into the chimney to roost for the night? Come join us for an evening of snacking and bird watching! 🐦🍴🍇✨🐦

**Who**: Anyone who wants to join!
**When**: Thursday, September 29th 2016, 5pm - 7pm (local time).
**Where**: School lawn at [Chapman Elementary School](https://goo.gl/maps/7gbsoCCD2HC2) 
**Snacks**: While we'll bring some snacks, if you bring some more, no one will complain. 🎊
**Clothes**: It will be chilly, so wear warm clothes and bring extra!

This event is organized under our Rails Girls Summer of Code [Code of Conduct](http://railsgirlssummerofcode.org/about/code-of-conduct/).

RSVP with a comment please. Your friends are welcome too! 👬👭👫👪

**Comment by jeenalee** [comment]
cc @fitzgen @malisas @slnovak

**Comment by malisas** [comment]
See you there!!! 😊

**Comment by fitzgen** [comment]
👍

**Comment by stefan-pdx** [comment]
I'm in!!!

**Comment by max-mapper** [comment]
awesome meetup idea, i'll be there!

**Comment by jeenalee** [comment]
@maxogden Woohoo! bring friends!! :D We'll get there early to get a good spot, and we will share gps coordinates with everyone!

**Comment by jeenalee** [comment]
This is where we are! We're on the hill SW from the school, behind the goal post, closer to Pettygrove st.

https://goo.gl/maps/MFmWHjgNvk42
