### ISSUE TITLE
End of RGSoC 2016 - Celebration in San Francisco @Github

### ISSUE THREAD

**Issue by go-bears** [rails-girls-summer-of-code/announcements#6]
We welcome everyone from our community to join us for a small get-together in San Francisco to celebrate the very last day of RGSoC 2016 :tada:

Who: anyone who wants to join; past, present and future participants, volunteers, and organisers!
What: a small informal get-together to chat and get to know our community and celebrate yet another successful RGSoC!

When: Friday, September 30th 2016, 5:30 pm Pacific Standard Time
Where: Github, 88 Colin P. Kelly Jr.

Some snacks and  drinks will be available from at the start of the evening. This event is organised under our Rails Girls Summer of Code Code of Conduct; we ask all attendees to read it and behave in accordance with our CoC. Thank you! :heart:

Please RSVP with a comment below before Thursday, 17:00 PST

**Comment by seemaullal** [comment]
I'll be there!

**Comment by cachar** [comment]
I'll be there! :)

**Comment by avh4** [comment]
✅

**Comment by jleven** [comment]
I'll be there! 👏

**Comment by heecho** [comment]
+1

**Comment by arbonap** [comment]
I'll be there 🍒
Also, I hear @mathildemouw will be there ✨

**Comment by mathildemouw** [comment]
I'll be there for a bit with my SO.
