### ISSUE TITLE
End of RGSoC 2016 — Celebration in Prague @ Basta brewery

### ISSUE THREAD

**Issue by dariasamo** [rails-girls-summer-of-code/announcements#7]
Let's celebrate the end of our summer experience with RGSoC in Prague, Czech Republic! Come join us for a beer and (not only) tech talk!

**Who:** XYZ team members: Veronika and Daria, coaches Josef and Jano, and members of Women in Tech Prague meetup. Anyone who wants to join is welcome too.
**When:** Thursday, September 29
**Where:** [Pivovar Basta](http://www.ubansethu.cz/cz/pivovar/)

**Comment by hovancik** [comment]
Gonna be there ;]
